### ISSUE TITLE
(gedaan) toevoegen van algemeen movement model (political / cultural / literary movements)

### ISSUE THREAD

**Issue by martijnbentum** [martijnbentum/region#10]
- er staan nog geen political movements of cultural movements die we kunnen toevoegen- dat is wel erg gewenst.

Movement
  Name: CharField
  Location: ForeignKey UserLoc
  Founded: Integer (year)
  Closure: Integer (year)
  Type: ChoiceField (literary, political, cultural)
  Notes: TextField

**Comment by martijnbentum** [comment]
Ik heb Literary Movement toegevoegd met de velden: name, location, founded, closure, notes.

Als political en cultural movements de zelfde velden hebben, dan moet er misschien een algemeen Movement model gemaakt worden waarbij aangegeven kan worden of het om een cultural, political of literary movement gaat?

**Comment by MargueriteCorporaal** [comment]
Ja dat klinkt als een uitstekend idee, Martijn! Doe het inderdaad maar zo.

**Comment by martijnbentum** [comment]
Ik heb het aangepast in het issue.

**Comment by martijnbentum** [comment]
Gedaan
Sluit jij het issue als je het goed vindt zo

**Comment by MargueriteCorporaal** [comment]
Hallo Martijn, krijg dit issue maar niet gesloten- sorry. Wil jij dat doen want van mij akkoord?

**Comment by martijnbentum** [comment]
Hoi, ik denk dat het komt omdat ik deze heb aangemaakt
Ik heb een approved label gemaakt, dan kan je die toevoegen als je het issue niet kan sluiten
