### ISSUE TITLE
Editors als optie toevoegen bij Periodical

### ISSUE THREAD

**Issue by MargueriteCorporaal** [martijnbentum/region#11]
toevoegen Person Periodical relation & person Periodical relation role

Kan dat, Martijn? Er zijn bijvoorbeeld tijdschriften zoals Shan Van Vocht waarbij ik nu wel de uitgever kan invoeren maar niet het belangrijke feit dat Anna Johnston en Alice Milligan de editors waren.

**Comment by martijnbentum** [comment]
Deze relatie zou mogelijk weer indirect kunnen. Een text heeft een person relatie (editor) en de tekst linkt met publicatie en publicatie met periodical.

Bij een tijdschrift is het misschien niet altijd mogelijk of makkelijk om per tekst te achterhalen wie de editor was. Er zou dan een personPeriodicalRelation toegevoegd kunnen worden.

**Comment by MargueriteCorporaal** [comment]
Mmmm, weet niet of dat goed uitpakt. Er is niet zozeer een editor per tekst maar per periodical. Valt daar dan een person to periodical relatie te realiseren, met als rol editor?

**Comment by martijnbentum** [comment]
added a person periodical relation (see add person / periodical)

**Comment by MargueriteCorporaal** [comment]
Werkt goed nu!
