### ISSUE TITLE
Person to publication relation

### ISSUE THREAD

**Issue by MargueriteCorporaal** [martijnbentum/region#12]
Hallo Martijn, ik zou graag bij personen willen kunnen aangeven dat ze veel betrokken waren bij een tijdschrift als contributor. Bijvoorbeeld Anna Johnston schreef voor The Nation. Kun je zulke relaties ook faciliteren?

**Comment by martijnbentum** [comment]
Ik zou deze relaties indirect laten. De database linkt schrijvers aan teksten en teksten aan tijdschriften. De link tussen een schrijver als contributor voor een tijdschrift bestaat dan dus al. 

Als je een schrijver wil linken aan een tijdschrift zonder dat er teksten in de database staan dan heb je de relatie wel nodig. Is dat het geval?

**Comment by MargueriteCorporaal** [comment]
Ja, dat is het geval- Alice Milligan en Anna Johnston schreven bijvoorbeeld voor andere tijdschriften en waren daar als editors bij betrokken maar dat zijn niet de tijdschriften waar hun teksten instaan.

**Comment by martijnbentum** [comment]
Dit  wordt opgelost met person periodical relation
