### ISSUE TITLE
Jaargang tijdschrift

### ISSUE THREAD

**Issue by MargueriteCorporaal** [martijnbentum/region#13]
Ik kan nu per tijdschrift steeds een jaargang ingeven maar het komt straks voor dat verhalen in verscheidene edities van het zelfde tijdschrift staan- bijvoorbeeld 1901 en 1905 van Harper’s Monthly Magazine. Hoe kan deze differentiatie vorm krijgen? Ik vul nu steeds bij een tekst publication in en kan dan wel paginanummers invoeren maar geen jaareditie.

**Comment by martijnbentum** [comment]
Voor Harper's Monthly Magazine kan een periodical aangemaakt worden. Voor de verschillende edities kunnen verschillende publicaties aangemaakt worden. De publicaties kunnen gelinkt worden met de periodical

**Comment by MargueriteCorporaal** [comment]
Dat klinkt als een prima oplossing. Wordt Periodical dan een aparte categorie, net als Text?

**Comment by martijnbentum** [comment]
Ja inderdaad en deze is al toegevoegd
