### ISSUE TITLE
Illustratie matchen met verhaal

### ISSUE THREAD

**Issue by MargueriteCorporaal** [martijnbentum/region#14]
Nog iets: als ik een illustratie invoeg nu (met illustrator) dan matcht hij met een publicatie (journal, nog niet met specifieke jaarrditie). Kunnen we ook matchen met de tekst waar de illustratie bij staat?

**Comment by martijnbentum** [comment]
De publicatie komt overeen met de jaareditie. Het journal kan toegevoegd worden bij periodical en de specifieke jaareditie kan dan gelinkt worden.

Bij periodical voer je het tijdschrift in.
Bij publicatie voer je de specifieke editie in

**Comment by MargueriteCorporaal** [comment]
Klinkt goed zo!
