### ISSUE TITLE
markeringen entry complete

### ISSUE THREAD

**Issue by MargueriteCorporaal** [martijnbentum/region#16]
Add 'complete' field for:
-text
-publication
-publisher
-illustration
-person
-movement
-periodical

Giulia en Chris vroegen zich af of we een entry met een functie kunnen markeren als compleet of incompleet zodat we altijd kunnen zien waar we nog data aan moeten toevoegen. Is dat mogelijk- dat de auteur dat aanmerkt en dat als een entry compleet is we nog controleren en afvinken?

**Comment by martijnbentum** [comment]
I have edited the issue a bit did I miss anything that should have a complete field

**Comment by MargueriteCorporaal** [comment]
Hi Martijn, what we mean is that we would like to have the possibility to earmark an entry that is complete and to be able to distinguish it from entries where data are still missing (like year of publication, page numbers). Would that be possible?

**Comment by martijnbentum** [comment]
Yes I will implement it

**Comment by martijnbentum** [comment]
I have created a setup for marking entries as complete and approved (see screen shot).
If the entry is complete the single checkmark checkbox can be checked. If the entry is approved the double checkmark checkbox can be checked. If this is ok I will implement further.
<img width="903" alt="Screen Shot 2020-04-21 at 10 15 48" src="https://user-images.githubusercontent.com/19554953/79842654-6b439100-83b9-11ea-88c7-e3b76ca57267.png">

**Comment by MargueriteCorporaal** [comment]
That looks fine to me, Martijn!

**Comment by martijnbentum** [comment]
added a complete and approved field for:
-text
-publication
-publisher
-illustration
-person
-movement
-periodical

**Comment by MargueriteCorporaal** [comment]
Perfect- approved!
