### ISSUE TITLE
Werken die uit meer delen bestaan

### ISSUE THREAD

**Issue by MargueriteCorporaal** [martijnbentum/region#17]
Giukia heeft in haar corpus veel romans die uit 2 of 3 delen bestaan. Kun je misschien bij publications het veld multi-volume novels en single-volume novel in plaats van novel aanmaken?

Chris komt verhalen tegen in een bundel verzamelde werken die uit meer delen bestaan. Hij wil graag kunnen aangeven in welk volume een verhaal dan zit. Hoe kunnen we zo'n weergave het beste realiseren?

**Comment by martijnbentum** [comment]
A publication can already link to multiple texts. You can add a text and when you hit save you can add another text (i can change this to immediately show multiple fields)

We should discuss how to deal with collections and volume numbers
maybe we should move issue and volume to publication?

**Comment by MargueriteCorporaal** [comment]
Martijn, I think it would indeed make more sense to shift issue and volume to publication- that would work best for the periodical publications in any case.

**Comment by martijnbentum** [comment]
Ok, I will close this issue because it is already addressed in another issue
