### ISSUE TITLE
Add location field for Text (Locaties bij settings van romans)

### ISSUE THREAD

**Issue by MargueriteCorporaal** [martijnbentum/region#19]
Martijn, kun je naast settings ook bij teksten locations als functie toevoegen, op dezelfde manier als bij publicaties: weergave van geolocation, fictionele locatie of meerdere locaties? We zien dit graag gerealiseerd en dan kunnen settings bovendien ook op een map gevisualiseerd worden. We zien overigens hier ook graag een drop down menu waarbij we plaats, regio en land kunnen invullen of selecteren.

**Comment by martijnbentum** [comment]
Should this be instead of 'setting' or a separate field?

**Comment by MargueriteCorporaal** [comment]
It could replace setting indeed- it would work better that way.

**Comment by MargueriteCorporaal** [comment]
Sorry, correction: please create this as a separate identifier of a real life location in addition to setting. Setting is more the description in the text like "a village in the North West of Ireland" or "Gurteen"-  location could then refer to Ballina or the real Gurteen in co. Mayo.

**Comment by martijnbentum** [comment]
Location(s) can be added to a text

**Comment by MargueriteCorporaal** [comment]
This works well now.
