### ISSUE TITLE
volume and issue should move to publication (Jaaredities van een tijdschrift of krant)

### ISSUE THREAD

**Issue by MargueriteCorporaal** [martijnbentum/region#20]
volume and issue should move to publication

We kunnnen nu een periodical invoeren en een tijdschrift als publicatie met een jaar. Het probleem is echter dat volumes niet synchroon lopen met kalenderjaren: The Idler is volume 1 tot juli 1892, daarna wordt het volume 2 tot juli 1893. Ik kwam bij verhalen van Frank James Mathew in de problemen dat het nu lijkt alsof de verhalen in dezelfde publicatie staan terwijl het niet zo is (andere volume). Is het zinnig om voor publicatie bij tijdschrift naast jaar juist daar volume en issue op te nemen?

**Comment by martijnbentum** [comment]
I think this is solved by the periodical publication relation.
You can add the volume and issue number there.

I can move volume and issue to publication if it is a better place for it
however you could loose some current entries and seems better placed at the relation between periodical & publication

**Comment by MargueriteCorporaal** [comment]
I nonetheless think that volume and issue should move to publication. It is a specific issue (publication) of a title (periodical). E.g. title is Harper's Weekly. Publication is Harper's Weekly vol. 20, issue 5.

**Comment by martijnbentum** [comment]
Ok
Shall I remove it from the periodical publication relation?

**Comment by MargueriteCorporaal** [comment]
Yes, please, Martijn!

**Comment by MargueriteCorporaal** [comment]
Thanks for implementing this.
