### ISSUE TITLE
Periodical location

### ISSUE THREAD

**Issue by MargueriteCorporaal** [martijnbentum/region#21]
Would it be possible to add location to periodical? Right now I can only insert foundation and closure dates- but it is also relevant where a periodical was published. When a journal is mentioned because a writer was editor of it, but it does not feature as part of a publication entry, we'd miss out on that information (for example, that a person edited a periodical in Lahore, India).

**Comment by martijnbentum** [comment]
Yes, I will implement it

**Comment by martijnbentum** [comment]
you can add one or more locations to periodical

**Comment by MargueriteCorporaal** [comment]
Perfect!
