### ISSUE TITLE
Text to text relation should be directional

### ISSUE THREAD

**Issue by martijnbentum** [martijnbentum/region#22]
Text A is translation of Text B
Text B is translated by Text A

**Comment by MargueriteCorporaal** [comment]
Rather, text B is a translation of text A? Can you indicate how we can mark which text is the original and which is the translation?

**Comment by martijnbentum** [comment]
Solution 1:
Genre is expanded with review, translation
Genre is changed so that you can add multiple genres
You can indicate on the text itself whether it is a review or a translation

Solution 2:
New field: text_type with the categories review, translation

Solution 3:
You can only enter text relations on the secondary text. E.g. if the text is review you can enter the relation to the text it is a review of. idem for translation.

Solution 4:
The possibility to add text relations when adding a text is removed
Create a separate form where you can enter text relations

**Comment by MargueriteCorporaal** [comment]
I’d say a combination of solution 2 and 3 would work best- but let’s discuss this with the group in our next meeting.

**Comment by MargueriteCorporaal** [comment]
Number 2- approved

**Comment by martijnbentum** [comment]
text_type with the categories review, translation is implemented

**Comment by MargueriteCorporaal** [comment]
Approved!
