### ISSUE TITLE
Add full date for publications

### ISSUE THREAD

**Issue by martijnbentum** [martijnbentum/region#26]
Publications should have a date field (day/month/year) to distinguish newspaper editions

**Comment by martijnbentum** [comment]
Changed the year field to a date field. The field accepts different levels of specificity (year; year-month; year-month-day; etc)
You can enter the date according to the following format:

                                                                                            
                   (format)                                                                                                                    
day              1999-12-04    Y-M-D                                                                                                         
month         1999-12           Y-M                                                                                                           
year             1999y              <integer>y                                                                                                    
decade        200d               <integer>d     1990-2000                                                                                      
century        20c                 <integer>c     1900-2000                                                                                      
millenium     2m                  <integer>m     1000-2000                                                                                      
                                                                                                                                        
For december fourth 1999 you type: 1999-12-04                                                                                           
                                                                                                                                        
Alternative formats                                                                                                                     
                                                                                                                                        
(format)             (Alternative format)                                                                                                
2c                       2nd century                                                                                                         
4m                      4th millenium                                                                                                       
1999y                 1999                                                                                                                
1999-01             January 1999                                                                                                        
1999-01-31       January 31, 1999

**Comment by MargueriteCorporaal** [comment]
Perfect! Approved
