### ISSUE TITLE
Location homonyms within the same country

### ISSUE THREAD

**Issue by GiuliaBruna** [martijnbentum/region#28]
When selecting a location which has a homonym within the same country there are two identical suggestions that pop up and it is impossible to know which one is which. For instance "Richmond | United Kingdom" is both a place near London and a town in Yorkshire. If I need to select one or the other how can I tell the difference? Could you add region specificity to the town? Thank you.

**Comment by GiuliaBruna** [comment]
I am just posting here another case of location homonym just to keep a record: Mount Pleasant | United States. There are at least 5 locations with that name that pop up and Mount Pleasant cities in South Carolina, Texas, Iowa and more. In the case of my writer -- John Watson -- I was interested in selecting Mount Pleasant in Iowa but I am not sure which one I selected in the end! Thank you.

**Comment by GiuliaBruna** [comment]
Another case of homonymy (see above): Westfield in the United States (For illustrator Frederick C. Gordon I would need Westfield, New Jersey.

**Comment by martijnbentum** [comment]
Locations show region name if available.
I also added the gps location to further disambiguate the locations (e.g. richmond cannot be distinguished based on the region information available in the database).

Let me know if this works for you

**Comment by GiuliaBruna** [comment]
It works perfect for the American locations, thanks. Re UK locations such as the infamous Richmond, there is still disambiguation. The GPS coordinates only show if you were to insert a location from anew but not when you want to select it from the drop down menu. Could GPS locations always be shown perhaps to avoid disambiguation? Hope you can see the screeshots. I guess we can discuss on Thursday.

From the Add Location Section of the Database
<img width="1238" alt="Screenshot 2020-05-25 at 17 57 29" src="https://user-images.githubusercontent.com/64974854/82828387-37282800-9eb1-11ea-96ca-25a6c3a8d505.png">

From the Person Section of the Database
<img width="654" alt="Screenshot 2020-05-25 at 18 00 36" src="https://user-images.githubusercontent.com/64974854/82828568-a56cea80-9eb1-11ea-8048-1615f51a1b4c.png">

**Comment by GiuliaBruna** [comment]
I will close this specific issue since it will be part of the enhancement at large of the location feature as we discussed in our meeting on May 28th.
