### ISSUE TITLE
Reorganize Locations

### ISSUE THREAD

**Issue by martijnbentum** [martijnbentum/region#33]
-locations should be editable
-multiple regions and or countries should be addable to a location

**Comment by MargueriteCorporaal** [comment]
Yes, that’s what we would like to mark in our data!

**Comment by martijnbentum** [comment]
-Locations can now be edited and deleted
-changed the help info to explain how to work with locations
- geo locations need to be added from the database after creating them

**Comment by MargueriteCorporaal** [comment]
Approved
