### ISSUE TITLE
Add search field to list overviews

### ISSUE THREAD

**Issue by martijnbentum** [martijnbentum/region#34]
Add a search field to Text, Publication, Publisher, Illustration, Person, Location, Movement & Periodical

You search by entering search terms. By default, the words are matched independently.
Entering:
<pre><code>at a </code></pre>
Will search for entries with 'at' and 'a'
If you want to search for 'at a' use:
<pre><code>at a *combine</code></pre>

The *combine term is a special term. Other special terms are:
*complete, *incomplete (to find entries that are complete or incomplete)
*approved, *unapproved  (to find entries that are approved or unapproved)
*and (whether all fields should contain the search term(s), see below)

The search terms are matched to all fields of the model. For example, searching texts with:
<pre><code>London</code></pre>

You can find the following entries: 

- Gomer on the "Better Land": And a Letter from London
- A Sunday Wedding in Fleet Street

The second entry is found because the setting contains 'London'
If you only want to search for 'London' in the title use:
<pre><code>London $title</code></pre>

You can use other field names as well (e.g. language or genre), just prepend the $

You can also use multiple field names, for example if you search texts with:
<pre><code>short $title $genre</code></pre>
You find many entries where either short is in the title or in the genre field. You can use the special term *and to only look for entries with short in both the title and genre field:
<pre><code>short $title $genre *and</code></pre>

**Comment by MargueriteCorporaal** [comment]
Approved
