### ISSUE TITLE
Unable to add new "genre" category - new genre categories gets added to "copyright" field instead

### ISSUE THREAD

**Issue by GiuliaBruna** [martijnbentum/region#35]
I was trying to add "Appendix" as an additional Genre category. However, when I did so, the first time, the Appendix category wouldn't show together with Introduction, Preface, novel, etc. When I tried a second time, it says "copyright with this name already exists". 

<img width="628" alt="Screenshot 2020-06-04 at 08 32 53" src="https://user-images.githubusercontent.com/64974854/83722856-fdd48280-a63d-11ea-9233-6110bba091f1.png">

It seems that the new Genre category I had added actually gets added under another field, the "Copyright" one.

<img width="999" alt="Screenshot 2020-06-04 at 08 35 36" src="https://user-images.githubusercontent.com/64974854/83723082-602d8300-a63e-11ea-9750-d01bbad89574.png">

Thanks for your help! BTW, the enabled search function works great!

**Comment by martijnbentum** [comment]
I will fix it

**Comment by martijnbentum** [comment]
I fixed it and also added Appendix to the genres

**Comment by martijnbentum** [comment]
I will remove it from copy right

**Comment by GiuliaBruna** [comment]
Works perfect now, thanks.
