### ISSUE TITLE
Problem with viewing publications

### ISSUE THREAD

**Issue by MargueriteCorporaal** [martijnbentum/region#38]
When I try to view the publications in the database, I receive ‘ error’ on my screen. I’m adding a screenshot. I don’t have the problem when I want to view texts or persons.

Additionally, I noticed that titles show up double when I press view texts. Initially I thought that somehow new texts had been added twice by mistake- but I now suspect that ‘text’ and ‘publication’ are both listed here (and that I shouldn’t delete one of these). Could you please check? 
![D1F41C18-1BCB-45A1-83C4-DF19AA6BF08A](https://user-images.githubusercontent.com/62671475/93852847-0f0bd280-fcb3-11ea-9f48-a094299930cd.jpeg)

**Comment by martijnbentum** [comment]
Publication view is working
Double text entries seems to be a problem. I made a new issue
