### ISSUE TITLE
locaties buiten Europa toevoegen

### ISSUE THREAD

**Issue by MargueriteCorporaal** [martijnbentum/region#4]
- Ik kan bij publishers geen locatie toevoegen zoals bijvoorbeeld New York.

**Comment by martijnbentum** [comment]
Ik heb nu alleen steden binnen Europa toegevoegd om de database niet onnodig vol te stoppen met steden die niet gebruikt worden.
Kan je ongeveer aangeven van welke gebieden steden gebruikt gaan worden?
Als dat niet kan zal ik iets anders bedenken.

**Comment by MargueriteCorporaal** [comment]
Hallo Martijn, een stad als Galway in Ierland die veel gebruikt zou moeten worden, staat niet bij Locations. Gebieden in Europa die ik verwacht: Ierland, Noord Ierland & Verenigd Koninkrijk, Frankrijk, Duitsland, Vlaanderen, Nederland, Italië, Spanje, Zweden, Denemarken, Noorwegen, Polen, Hongarije. En wat er niet in zit zijn belangrijke steden in Noord Amerika waar veel publishers zitten: Toronto, Montreal, New York, Boston, Philadelphia, Chicago, San Francisco. Die toevoegen zou moeten dekken.

**Comment by MargueriteCorporaal** [comment]
Hallo Martijn, ook steden als St Petersburg kan ik niet invoeren nu

**Comment by martijnbentum** [comment]
Locaties kunnen nu toegevoegd worden (Add > Location)
Ik heb een <Help> tab toegevoegd met uitleg. Als er iets niet duidelijk is of het werkt niet, dan hoor ik het graag.

**Comment by MargueriteCorporaal** [comment]
Werkt goed nu- approved
