### ISSUE TITLE
Search Function and Multiple Entries Visualized (one text entered in reality)

### ISSUE THREAD

**Issue by GiuliaBruna** [martijnbentum/region#42]
I did a text search writing "Jamie"in the general search function -- one of the texts that you had flagged as double and that I had just changed adding [American Edition, Canadian Edition] etc. Here is what I see:

<img width="1381" alt="Screenshot 2020-10-16 at 10 13 33" src="https://user-images.githubusercontent.com/64974854/96233762-cd600600-0f98-11eb-89a7-c490757a2c47.png">

<img width="1270" alt="Screenshot 2020-10-16 at 10 13 41" src="https://user-images.githubusercontent.com/64974854/96233773-d05af680-0f98-11eb-9844-672a9cf19b48.png">
 
The texts however have not been inserted 4 times, meaning there aren't 4 texts with the same name in the Canadian edition. If I click on one of those and change them in the title or something then in the search function all 4 will appear changed if I use the search function again (this happened when I added Canadian Edition or American edition).

I have no other way but to use the search function to retrieve texts if I need to edit them back. But I am pretty sure I did not put them in 4 times for sure, hence I think it is a bug or something not working properly for me when I save the entry?

Thanks for your help.

**Comment by martijnbentum** [comment]
Thanks for the example. I will fix it.

**Comment by martijnbentum** [comment]
Fixed

**Comment by GiuliaBruna** [comment]
Super! Thanks a million. I can visualize things correctly now. Will close this thread.
