### ISSUE TITLE
Soms lijkt het systeem een invoering van data niet te pakken

### ISSUE THREAD

**Issue by MargueriteCorporaal** [martijnbentum/region#6]
Soms lijkt het systeem een invoering van data niet te pakken- dan doe ik het opnieuw maar dan komt een naam 2 of 3x in de lijst.

**Comment by martijnbentum** [comment]
Wat gebeurt er als het systeem de data niet lijkt te pakken?

**Comment by MargueriteCorporaal** [comment]
Dan krijg ik error op scherm met daaronder veel computertaal. Ga ik vervolgens naar de lijst dan zijn de data blijkbaar toch wel opgeslagen.

**Comment by martijnbentum** [comment]
Welke data voer je in?
Zou je een screenshot kunnen toevoegen?
