### ISSUE TITLE
Person repeated 5 times: bug?

### ISSUE THREAD

**Issue by GiuliaBruna** [martijnbentum/region#67]
Nils, the student assistant, flagged me a problem with an entry in the 'person' category. Ge inserted a new 'unknown' person whose details known are only his initials B. F. This person is a Norwegian translator of Daudet's text Lettres de Mon Moulin. The entry, however, is repeated 5 times (and he did not put it in 5 times!).

<img width="1088" alt="Screenshot 2021-06-17 at 17 33 47" src="https://user-images.githubusercontent.com/64974854/122428437-2f429680-cf92-11eb-9d49-42c46b245283.png">

Could this be fixed without eliminating connections?

Many thanks, Giulia

**Comment by martijnbentum** [comment]
Hi Gulia & Nils,

I have deleted the duplicate entries and I think without eliminating connections.
I looked at the timestamps of the entries and saw that there was some time between the entries (the entries were not save within milliseconds of each other). If the saves were close together a bug would be more likely. I could not recreate the bug: I entered similar entries but this did not create duplicates. This not to say that there is no bug, but I cannot find it yet.

There is a mechanism that guards against duplicates, but for persons this takes first name, last name and birth date, so for persons that do not have a lot of info this will not work ;-(.

Nils maybe we can meet sometime via zoom/skype, maybe we can discover what happened? I am available today, Tuesday afternoon, Wednesday afternoon or next Friday.

Best,
Martijn
