### ISSUE TITLE
Person to person relatie toevoegen

### ISSUE THREAD

**Issue by MargueriteCorporaal** [martijnbentum/region#7]
PersonToPersonRelation
person1: Foreignkey Person
person2: Foreignkey Person
relationtype: (ChoiceField) Friendship, ...

Ik kan wel voor allerlei personen gegevens invoeren maar kan dan geen person to person relaties maken. Moet dat nog ontwikkeld worden? En hoe verbind ik de personen dan met literaire en politieke bewegingen?

**Comment by martijnbentum** [comment]
Ik kan person-to-person relatie toevoegen. Wat zijn het type relaties tussen personen die toegevoegd worden?

**Comment by MargueriteCorporaal** [comment]
Die relaties kunnen heel gevarieerd zijn: vriendschap, betrokken bij zelfde politieke of literaire beweging of kring, samenwerking als editors of auteurs of als auteur-kunstenaar. Kom je hier verder mee?

**Comment by martijnbentum** [comment]
-Betrokken bij dezelfde politieke / literaire beweging gaat denk ik via Movement?
-Samenwerking als editor / auteur / illustrator gaat via tekst en of publicatie

Zou het er ongeveer zo uit kunnen zien?
PersonToPersonRelation
  person1: Foreignkey Person
  person2: Foreignkey Person 
  relationtype:  (ChoiceField) Friendship, ...

**Comment by MargueriteCorporaal** [comment]
Dat lijkt me echt prima zo om alle relaties in kaart te kunnen brengen
