### ISSUE TITLE
gemakkelijker titels vanuit publicatie 1 naar publicatie 2 importeren

### ISSUE THREAD

**Issue by martijnbentum** [martijnbentum/region#8]
- Als een collectie in Dublin, London en New York is uitgegeven met exact dezelfde inhoud en paginering, dan moet ik alles opnieuw in typen. Kun je gemakkelijker titels vanuit publicatie 1 naar publicatie 2 importeren?

**Comment by martijnbentum** [comment]
Ik ga iets proberen te bedenken

**Comment by martijnbentum** [comment]
With publication you can now make a copy with 'Save as'. The user gets a message that a copy has been made and edits should be saved with 'Save'. Multiple presses on 'Save as' will result in multiple copies.

**Comment by MargueriteCorporaal** [comment]
This works well now, though I'm afraid I pushed save as twice on two occasions ;). Those publication entries will have to be removed eventually.
