### ISSUE TITLE
Deleting entries (Verwijderen van entries)

### ISSUE THREAD

**Issue by martijnbentum** [martijnbentum/region#9]

**Comment by martijnbentum** [comment]
Ik wil graag een manier bedenken waardoor niet iedereen zomaar dingen kan verwijderen, maar dat kost wat tijd.

**Comment by martijnbentum** [comment]
Only users with the correct privileges can add, edit or delete entries.
Before you delete an entry you get a confirmation screen. 
Deleting an entry is final (no undo). Automatic backups are created for when something bad happens.

Chris, Giulia, Marguerite & Ninge can add, edit and delete entries.

**Comment by MargueriteCorporaal** [comment]
Approved- it works well!
